export { default as JudgementImage } from './images/Judgement.jpg';
export { default as JusticeImage } from './images/Justice.jpg';
export { default as LoversImage } from './images/Lovers.jpg';
export { default as MagicianImage } from './images/Magician.jpg';
export { default as MoonImage } from './images/Moon.jpg';
export { default as ReverseCardImage } from './images/Reverse-card.jpeg';
export { default as StarImage } from './images/Star.jpg';
export { default as StrenghtImage } from './images/Strenght.jpg';
export { default as SunImage } from './images/Sun.jpg';
export { default as TemperanceImage } from './images/Temperance.jpg';
export { default as TowerImage } from './images/Tower.jpg';
export { default as WhellOfFortuneImage } from './images/Whell of fortune.jpg';
export { default as WorldImage } from './images/World.jpg';
export { default as SixPentaclesImage } from './images/6 of pentacles.jpg';
export { default as SevenPentaclesImage } from './images/7 of pentacles.jpg';
export { default as EightPentaclesImage } from './images/8 of pentacles.jpg';
export { default as NinePentaclesImage } from './images/9 of pentacles.jpg';
export { default as TenPentaclesImage } from './images/10 od pentacles.jpg';
export { default as KingPentaclesImage } from './images/King of pentacles.jpg';
export { default as QueenPentaclesImage } from './images/Queen of pentacles.jpg';
export { default as PagePentaclesImage } from './images/Page of pentacles.jpg';
export { default as AcePentaclesImage } from './images/Ace of pentacles.jpg';
export { default as ChariotImage } from './images/Chariot.jpg';
export { default as DeathImage } from './images/Death.jpg';
export { default as DevilImage } from './images/Devil.jpg';
export { default as EmpressImage } from './images/Empress.jpg';
export { default as FoolImage } from './images/Fool.jpg';
export { default as HangedManImage } from './images/Hanged Man.jpg';
export { default as HermitImage } from './images/Hermit.jpg';
export { default as HierophantImage } from './images/Hierophant.jpg';
export { default as HighPriestesImage } from './images/High priestess.jpg';
export { default as FivePentaclesImage } from './images/5 of pentacles.jpg';
export { default as FourPentaclesImage } from './images/4 of pentacles.jpg';
export { default as ThreePentaclesImage } from './images/3 of pentacles.jpg';
export { default as TwoPentaclesImage } from './images/2 of pentacles.jpg';
export { default as KnightWandsImage } from './images/Knight of wands.jpg';
export { default as AceWandsImage } from './images/Ace of wands.jpg';
export { default as PageWandsImage } from './images/Page of wands.jpg';
export { default as QueenWandsImage } from './images/Queen of wands.jpg';
export { default as KingWandsImage } from './images/King of wands.jpg';
export { default as TenWandsImage } from './images/10 of wands.jpg';
export { default as NineWandsImage } from './images/9 of wands.jpg';
export { default as EightWandsImage } from './images/8 of wands.jpg';
export { default as SevenWandsImage } from './images/7 of wands.jpg';
export { default as SixWandsImage } from './images/6 of wands.jpg';
export { default as FiveWandsImage } from './images/5 of wands.jpg';
export { default as FourWandsImage } from './images/4 of wands.jpg';
export { default as ThreeWandsImage } from './images/3 of wands.jpg';
export { default as TwoWandsImage } from './images/2 of wands.jpg';
export { default as AceSwordsImage } from './images/Ace of swords.jpg';
export { default as KnightSwordsImage } from './images/Knight of swords.jpg';
export { default as PageSwordsImage } from './images/Page of swords.jpg';
export { default as QueenSwordsImage } from './images/Queen of swords.jpg';
export { default as KingSwordsImage } from './images/King of swords.jpg';
export { default as TenSwordsImage } from './images/10 of swords.jpg';
export { default as NineSwordsImage } from './images/9 of swords.jpg';
export { default as EightSwordsImage } from './images/8 of swords.jpg';
export { default as SevenSwordsImage } from './images/7 of swords.jpg';
export { default as SixSwordsImage } from './images/6 of swords.jpg';
export { default as FiveSwordsImage } from './images/5 of swords.jpg';
export { default as FourSwordsImage } from './images/4 of swords.jpg';
export { default as ThreeSwordsImage } from './images/3 of swords.jpg';
export { default as TwoSwordsImage } from './images/2 of swords.jpg';
export { default as KnightCupsImage } from './images/Knight of cups.jpg';
export { default as KnightPentaclesImage } from './images/Knight of pentacles.jpg';
export { default as AceCupsImage } from './images/Ace of cups.jpg';
export { default as PageCupsImage } from './images/Page of cups.jpg';
export { default as QueenCupsImage } from './images/Queen od cups.jpg';
export { default as KingCupsImage } from './images/King of cups.jpg';
export { default as TenCupsImage } from './images/10 of cup.jpg';
export { default as NineCupsImage } from './images/9 of cup.jpg';
export { default as EightCupsImage } from './images/8 of cup.jpg';
export { default as SevenCupsImage } from './images/7 of cup.jpg';
export { default as FiveCupsImage } from './images/5 of cups.jpg';
export { default as SixCupsImage } from './images/6 of cups.jpg';
export { default as FourCupsImage } from './images/4 of cups.jpg';
export { default as ThreeCupsImage } from './images/3 of cups.jpg';
export { default as TwoCupsImage } from './images/2 of cups.jpg';
